#!/bin/bash
#
# Debian/Ubuntu Server Ağ Otomatik Yapılandırma
# 
# KULLANIM:
# --------
# Otomatik (mevcut DHCP IP'yi sabit yap):
#   curl -sSL bit.ly/net-setup | sudo bash -s -- auto
#
# Manuel IP belirt:
#   curl -sSL bit.ly/net-setup | sudo bash -s -- 192.168.1.100 192.168.1.1 8.8.8.8
#

set -e

# Root kontrolü
if [ "$EUID" -ne 0 ]; then 
    echo "HATA: Root yetki gerekli!"
    echo "Kullanım: sudo bash $0"
    exit 1
fi

echo "==================================="
echo "  Debian Network Setup"
echo "==================================="
echo

# Ağ bilgilerini topla
CURRENT_IP=$(hostname -I | awk '{print $1}')
INTERFACE=$(ip route | grep default | awk '{print $5}' | head -n1)
CURRENT_GW=$(ip route | grep default | awk '{print $3}')
CURRENT_DNS=$(grep nameserver /etc/resolv.conf | awk '{print $2}' | head -n1)

if [ -z "$CURRENT_IP" ]; then
    echo "HATA: Aktif IP bulunamadı!"
    echo "Önce DHCP ile bağlan."
    exit 1
fi

echo "Mevcut Durum:"
echo "  Interface : $INTERFACE"
echo "  IP        : $CURRENT_IP"
echo "  Gateway   : $CURRENT_GW"
echo "  DNS       : $CURRENT_DNS"
echo

# Parametreleri kontrol et
MODE="${1:-auto}"

if [ "$MODE" = "auto" ]; then
    echo "MOD: Otomatik (mevcut IP sabitlenecek)"
    STATIC_IP=$CURRENT_IP
    GATEWAY=$CURRENT_GW
    DNS=$CURRENT_DNS
    echo
elif [ "$#" -eq 3 ]; then
    echo "MOD: Manuel"
    STATIC_IP=$1
    GATEWAY=$2
    DNS=$3
    echo
elif [ "$#" -eq 1 ] && [ "$1" != "auto" ]; then
    echo "HATA: Geçersiz parametre!"
    echo
    echo "Doğru kullanım:"
    echo "  $0 auto                              # Otomatik"
    echo "  $0 192.168.1.100 192.168.1.1 8.8.8.8 # Manuel"
    exit 1
else
    echo "HATA: Eksik parametre!"
    echo
    echo "Doğru kullanım:"
    echo "  $0 auto                              # Otomatik"
    echo "  $0 192.168.1.100 192.168.1.1 8.8.8.8 # Manuel"
    exit 1
fi

# Yapılandırma özeti
echo "Uygulanacak Ayarlar:"
echo "  IP      : $STATIC_IP"
echo "  Gateway : $GATEWAY"
echo "  DNS     : $DNS"
echo "  Netmask : 255.255.255.0"
echo

# Countdown
echo "3 saniye içinde başlanacak... (Ctrl+C = iptal)"
sleep 1 && echo "2..."
sleep 1 && echo "1..."
sleep 1 && echo "Başlıyor..."
echo

# Yedek al
BACKUP_FILE="/etc/network/interfaces.backup.$(date +%Y%m%d_%H%M%S)"
if [ -f /etc/network/interfaces ]; then
    cp /etc/network/interfaces "$BACKUP_FILE"
    echo "✓ Yedek alındı: $BACKUP_FILE"
fi

# Yeni config yaz
cat > /etc/network/interfaces << EOF
# Auto-generated by debian-network-setup
# Backup: $BACKUP_FILE

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto $INTERFACE
iface $INTERFACE inet static
    address $STATIC_IP
    netmask 255.255.255.0
    gateway $GATEWAY
    dns-nameservers $DNS 8.8.8.8
EOF

echo "✓ Config yazıldı: /etc/network/interfaces"

# DNS config
cat > /etc/resolv.conf << EOF
nameserver $DNS
nameserver 8.8.8.8
EOF

chattr +i /etc/resolv.conf 2>/dev/null || true
echo "✓ DNS ayarlandı"

# Network restart
echo
echo "Ağ servisi yeniden başlatılıyor..."
if systemctl restart networking 2>/dev/null; then
    echo "✓ Servis başlatıldı (systemd)"
elif service networking restart 2>/dev/null; then
    echo "✓ Servis başlatıldı (sysvinit)"
else
    ifdown $INTERFACE 2>/dev/null || true
    ifup $INTERFACE 2>/dev/null || true
    echo "✓ Interface yenilendi"
fi

sleep 2

# Test
echo
echo "===================="
echo "  DURUM"
echo "===================="
ip addr show $INTERFACE | grep "inet " | awk '{print "IP: " $2}'

echo
if ping -c 2 -W 2 8.8.8.8 >/dev/null 2>&1; then
    echo "✓ İnternet çalışıyor!"
else
    echo "⚠ İnternet bağlantısı yok!"
    echo
    echo "Geri almak için:"
    echo "  mv $BACKUP_FILE /etc/network/interfaces"
    echo "  systemctl restart networking"
fi

echo
echo "Tamamlandı!"
echo "SSH kullanıyorsan yeni IP: $STATIC_IP"
